# -*- coding: utf-8 -*-
"""day-4_python_excercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OlarZ1XxCJlm5vovr9g12s_6FRf0foRc
"""

1.b
2.b
3.set
4.set
5. c

a= 17
b= 5
print(a//b)

a= 17
b= 5
print(a%b)

numbers=[10,20,30,40,50,60]
print(numbers[1:4])

set_a = {1,2,3,4}
set_b = {3,4,5,6}
print(set_a&set_b)

tup = (1,2,3)
tup(0)=10 --""""in tuple we cannot assign change the value"""

student ={"name": "john", "score": 85}
student["score"]=92
student["passed"]=True
print(len(student))

c = int(input())
f= (c*9/5+32)
print(round(f,2))

grades = [78,85,62,90,85,95,78]
c= set((grades))
print(c)
f= list(c)
print(f)
f.sort()
print(f)
print(min(f))
print(max(f))
print((f))
g=sum(f)/len(f)
print(g)

frontend_skills ={"HTML","CSS","javaScript","React"}
backend_skills ={"python","SQL","javaScript","Node"}
g=frontend_skills.union(backend_skills)
print(g)
c=frontend_skills.intersection(backend_skills)
print(c)
d=backend_skills.difference(frontend_skills)
print(d)

classroom = {
"S101": {"name": "Alice", "subjects": {"Math": 88, "Science": 92}},
"S102": {"name": "Bob", "subjects": {"Math": 75, "Science": 80}}
}
classroom["s103"] ={"name": "Charlie", "marks" :{"math":95,"Science":89}}
print(classroom)
d=classroom["S101"]["subjects"].values()
f=list(d)
print(f)
print(sum(d)/len(d))

classroom["S102"]["subjects"]["Math"] = 82
print(classroom)

bill_amount= 125.50
tax_amount=8/100*125.50
tip_amount=15/100*125.50
print(round(tax_amount,2))
print(round(tip_amount,2))
Grand_total=(bill_amount+tax_amount+tip_amount)
print(round(Grand_total,2))

numbers =[12,45,2,91,33,24,88,50,19,73]
print(numbers[3:7])
numbers.append(100)
print(numbers)
numbers.insert(0,5)
print(numbers)
numbers.sort(reverse=True)
print(numbers)
print(numbers,len(numbers))

inventory ={
    "laptop" :12,
    "mouse":50,
    "keyboard": 25,
    "monitor": 8
}

inventory["headphones"]=30
print(inventory)
inventory.update({"mouse":45})
print(inventory)
inventory.pop("monitor")
print(inventory)

in_stock_items=set((inventory.keys()))
print(in_stock_items)

in_stock_items=set((inventory.keys()))
discounted_items={"mouse","keyboard","webcam"}
x=in_stock_items.intersection(discounted_items)
print(x)
y=discounted_items-in_stock_items
print(y)

employee =("E402","Sarah Connor", "Engineering", 75000)
emp_id,emp_name,department,salary=employee
print(f"Employee {emp_name} {emp_id} works in {department} with salary of {salary}")
e=list(employee)
e[3]=82000
s=tuple(e)
print(s)

sales ={"monday":{"apples":10,"bananas":15,"oranges":8},
        "tuesday": {"apples":12,"bananas": 20, "oranges": 5},
        "wednesday":{"apples":8,"bananas":18,"oranges":12}
}
total_number_of_apples=sales["monday"]["apples"] + sales["tuesday"]["apples"] + sales["wednesday"]["apples"]
print(total_number_of_apples)
total_number_of_bananas=sales["monday"]["bananas"] + sales["tuesday"]["bananas"] + sales["wednesday"]["bananas"]
print(total_number_of_bananas)

difference=total_number_of_bananas-total_number_of_apples
print(difference)
"""--- banana sell the more when compare to apples"""

age = int(input("Enter your age:" ))
""" age = input("Enter your age: ") when we wont give the int it will take as a str"""
years_to_100 = 100 - age
""" print("You will turn 100 in " + years_to_100 + " years!") we neeed to use the f string formate to combine the str with int"""
print(f"You will turn 100 in {years_to_100} years!")

math=60
science=40
english=80
average=(math+science+english)/3
"followes the operator procedure"
is_passed = (average >= 50 and math > 50 and science > 50 and english > 50)
"""is_passed = average >= 50 and math > 50 or science > 50 or english > 50
we need to check the every condition"""
print(is_passed)
print("Average:",average)
print("passed:",is_passed)

tags = {"python", "coding", "python", "developer"}
user_profile = {
"username": "coder123",
"skills": tags,
"location": "New York"
}
print(user_profile)
x=set(tags)
print(x)
"""first_skill = tags[0] -- we cannot acess the set item by index"""
"""tags.add("backend") """
"""user_profile["location"].append("USA") --- string object has no method append"""

x=list(tags)
print(x[0])
print(x)
user_profile["skills"] = x
print(user_profile)
print(user_profile["skills"][0:])
x.append("backend")
"""in python the dictionary will look list directly"""
print(user_profile)
user_profile["location"]="USA"
print(user_profile)

coordinates = (10.5, 20.3, 30.1)
"""coordinates[0] = 12.0 -- we caanot chage the items in tuple"""
numbers = [1, 2, 3, 4, 5]
"""numbers.remove(10) --when theere is no element in the ilist the remove method will throw an error by using in and try and except we can prevent it"""

numbers.sort()
print(numbers)
"""sorted_numbers = numbers.append(6) --- when we use append with the variable it will return the NONE"""
numbers.append(6)
print(numbers)

inventory = {
"apple": 50,
"banana": 30,
"orange": 20
}

"""grape_qty = inventory["grape"] ---the value grap is not there in the dictionary"""
"""inventory.banana = inventory.banana + 10"""
"""keys_tuple = tuple(inventory.keys)"""

inventory["graps"]=60
print(inventory)
inventory["banana"]=30+10
print(inventory)
keys_tuple=tuple(inventory.keys())
print(keys_tuple)

